name: Sbt Dependency Graph

on:
  push:
    branches: [ main ]

jobs:
  submit-dependency-graph:
    name: Submit dependency graph
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: scalacenter/sbt-dependency-graph-action@v1
