
on:
  schedule:
    - cron: '0 0 * * 1,5' # every Monday and Friday
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Bloop Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.BLOOPOID_GITHUB_TOKEN }}
          author-email: bloop@vican.me
          author-name: Bloop Bot
